import 'dotenv/config'
import { createClient } from '@supabase/supabase-js'
import crypto from 'crypto'

const supabase = createClient(
  process.env.VITE_SUPABASE_URL,
  process.env.VITE_SUPABASE_ANON_KEY
)

const TARGET_EVENTS = 5000
const BATCH_SIZE = 500

function randomInt(min, max) {
  return Math.floor(Math.random() * (max - min + 1)) + min
}

function pick(list) {
  return list[randomInt(0, list.length - 1)]
}

function randomDispenseDate() {
  const today = new Date()
  const daysBack = randomInt(1, 365)
  today.setDate(today.getDate() - daysBack)
  return today.toISOString()
}

function quantityByCost(unitCost) {
  if (unitCost >= 1000) return 1
  if (unitCost >= 100) return randomInt(1, 3)
  return randomInt(1, 5)
}

function directionsByForm() {
  return pick([
    'Take as directed',
    'Take once daily',
    'Take twice daily',
    'Take three times daily',
    'Use as prescribed',
  ])
}

function indicationRandom() {
  return pick([
    'Acute condition',
    'Chronic therapy',
    'Follow-up prescription',
    'Emergency supply',
    'Specialty treatment',
  ])
}

async function loadAllRows(tableName, selectColumns) {
  let allRows = []
  let from = 0
  const pageSize = 1000

  while (true) {
    const { data, error } = await supabase
      .from(tableName)
      .select(selectColumns)
      .range(from, from + pageSize - 1)

    if (error) throw error
    if (!data || data.length === 0) break

    allRows = [...allRows, ...data]

    if (data.length < pageSize) break
    from += pageSize
  }

  return allRows
}

async function generateDispenseEvents5000() {
  console.log('Starting FalconMed Dispense Events Generator...')

  const patients = await loadAllRows('patients', 'id')
  console.log(`Loaded patients: ${patients.length}`)

  const inventory = await loadAllRows(
    'inventory',
    'id, pharmacy_id, drug_code, quantity_on_hand, unit_cost'
  )
  console.log(`Loaded inventory rows: ${inventory.length}`)

  const drugs = await loadAllRows(
    'drug_master_reference',
    'drug_code, generic_name, brand_name, strength, dosage_form'
  )
  console.log(`Loaded drug master rows: ${drugs.length}`)

  if (!patients.length) throw new Error('No patients found.')
  if (!inventory.length) throw new Error('No inventory found.')

  const drugMap = new Map(drugs.map((d) => [d.drug_code, d]))

  const usableInventory = inventory
    .map((item) => ({
      ...item,
      quantity_on_hand: Number(item.quantity_on_hand || 0),
      unit_cost: Number(item.unit_cost || 0),
    }))
    .filter((item) => item.quantity_on_hand > 5)

  if (!usableInventory.length) {
    throw new Error('No usable inventory with quantity > 5.')
  }

  const dispenseRows = []
  const medicationRows = []
  const inventoryDeductionMap = new Map()

  let attempts = 0

  while (dispenseRows.length < TARGET_EVENTS && attempts < TARGET_EVENTS * 20) {
    attempts++

    const patient = pick(patients)

    let item = pick(usableInventory)

    if (item.unit_cost >= 1000 && Math.random() < 0.85) {
      continue
    }

    const drug = drugMap.get(item.drug_code)

    if (!drug) continue

    const qty = quantityByCost(item.unit_cost)

    if (item.quantity_on_hand - qty < 0) continue

    item.quantity_on_hand -= qty

    const previousDeduction = inventoryDeductionMap.get(item.id) || 0
    inventoryDeductionMap.set(item.id, previousDeduction + qty)

    const dispenseDate = randomDispenseDate()
    const dispenseId = crypto.randomUUID()
    const medHistoryId = crypto.randomUUID()

    dispenseRows.push({
      id: dispenseId,
      patient_id: patient.id,
      pharmacy_id: item.pharmacy_id,
      drug_code: item.drug_code,
      generic_name: drug.generic_name || null,
      brand_name: drug.brand_name || null,
      strength: drug.strength || null,
      quantity_dispensed: qty,
      dispense_date: dispenseDate,
      dispensed_by: null,
      transaction_id: null,
      notes: 'Generated by FalconMed operational simulation',
      created_at: dispenseDate,
    })

    medicationRows.push({
      id: medHistoryId,
      patient_id: patient.id,
      pharmacy_id: item.pharmacy_id,
      drug_code: item.drug_code,
      generic_name: drug.generic_name || null,
      brand_name: drug.brand_name || null,
      strength: drug.strength || null,
      dosage_form: drug.dosage_form || null,
      quantity: qty,
      unit: 'unit',
      directions: directionsByForm(),
      duration_days: randomInt(5, 30),
      prescribing_doctor: pick([
        'Dr. Ahmed',
        'Dr. Sara',
        'Dr. Khalid',
        'Dr. Mariam',
        'Dr. Omar',
      ]),
      indication: indicationRandom(),
      inventory_transaction_id: null,
      created_at: dispenseDate,
      created_by: null,
    })
  }

  console.log(`Prepared dispense rows: ${dispenseRows.length}`)
  console.log(`Prepared medication history rows: ${medicationRows.length}`)

  for (let i = 0; i < dispenseRows.length; i += BATCH_SIZE) {
    const batch = dispenseRows.slice(i, i + BATCH_SIZE)

    const { error } = await supabase
      .from('patient_dispense_history')
      .insert(batch)

    if (error) {
      console.error('Dispense insert error:', error)
      throw error
    }

    console.log(`Inserted dispense rows ${i + 1} - ${i + batch.length}`)
  }

  for (let i = 0; i < medicationRows.length; i += BATCH_SIZE) {
    const batch = medicationRows.slice(i, i + BATCH_SIZE)

    const { error } = await supabase
      .from('patient_medication_history')
      .insert(batch)

    if (error) {
      console.error('Medication history insert error:', error)
      throw error
    }

    console.log(`Inserted medication rows ${i + 1} - ${i + batch.length}`)
  }

  console.log(`Updating inventory quantities for ${inventoryDeductionMap.size} inventory rows...`)

  let updatedCount = 0

  for (const [inventoryId, deductedQty] of inventoryDeductionMap.entries()) {
    const original = inventory.find((item) => item.id === inventoryId)

    if (!original) continue

    const newQty = Math.max(
      0,
      Number(original.quantity_on_hand || 0) - deductedQty
    )

    const { error } = await supabase
      .from('inventory')
      .update({
        quantity_on_hand: newQty,
        updated_at: new Date().toISOString(),
        last_updated: new Date().toISOString(),
      })
      .eq('id', inventoryId)

    if (error) {
      console.error('Inventory update error:', error)
      throw error
    }

    updatedCount++

    if (updatedCount % 500 === 0) {
      console.log(`Updated inventory rows: ${updatedCount}`)
    }
  }

  console.log(`Updated inventory rows: ${updatedCount}`)
  console.log('Dispense events generation completed successfully.')
}

generateDispenseEvents5000().catch((error) => {
  console.error('Dispense events generation failed:')
  console.error(error)
})